Refactored board so it's outside state.
jkatan/SokobanSolvers pull request #3
Opened 2020-08-13 22:34 UTC by npaganini

2020-08-13 22:35 UTC, npaganini commented
Creo que todavía se pueden sacar más cosas para afuera pero hay que analizarlo más!

2020-08-14 21:31 UTC, jkatan requested changes

2020-08-14 21:31 UTC, jkatan commented on src/GameBoard.java
> +    private Point playerPosition;
El playerPosition en esta clase se puede omitir, no? Así queda solo en el Gamestate.
Veo que solo usamos la posición del jugador en esta clase para imprimir @ en el mapa en el toString(), pero aún así veo que se lo pasamos al gameboard como parámetro desde afuera, así que calculo que no es necesario que tengamos el playerPosition en esta clase

2020-08-14 21:31 UTC, jkatan commented on src/SokobanSolver.java
> +        HashSet<Integer> gameBoardVisited = new HashSet<>();
Me gustó lo del HashSet<Integer>

2020-08-14 22:03 UTC, npaganini commented on src/GameBoard.java
> +    private Point playerPosition;
Lo pasé todo al GameBoard!

2020-08-14 22:04 UTC, merged